name: Deploy PR previews
concurrency: preview-${{ github.ref }}

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: github.event.action != 'closed'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - run: npm ci
      - run: npm run build

      - uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: dist
          preview-branch: gh-pages
          umbrella-dir: pr-preview
          action: auto
